/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aprendiendoJava_Ejemplo */

#ifndef _Included_aprendiendoJava_Ejemplo
#define _Included_aprendiendoJava_Ejemplo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aprendiendoJava_Ejemplo
 * Method:    nativeFoo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_aprendiendoJava_Ejemplo_nativeFoo
  (JNIEnv *, jclass);

/*
 * Class:     aprendiendoJava_Ejemplo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_aprendiendoJava_Ejemplo_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
